
/****** Object:  StoredProcedure [dbo].[PIncIncident$INC_INCIDENTModify]    Script Date: 6/28/2017 12:45:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER Procedure [dbo].[PIncIncident$INC_INCIDENTModify]
	@INCID int,
	@USERINCNO varchar(20),
	@STATUS char(10),
	@DATEENTERED datetime,
	@FORMHRID int,
	@FORMEMPNO char(25),
	@FORMFIRSTNAME varchar(50),
	@FORMSURNAME varchar(50),
	@DATECLOSED datetime,
	@INCTYPE_INJURY int,
	@INCTYPE_NEARMISS int,
	@INCTYPE_HAZARD int,
	@INCTYPE_ENVIMPACT int,
	@INCTYPE_PROPDAMAGE int,
	@INCTYPE_MOTOR int,
	@CONFIDENTIAL int,
	@INCIDENTDATE datetime,
	@INCIDENTTIME datetime,
	@REPORTDATE datetime,
	@REPORTTIME datetime,
	@REPORTBY_HRID int,
	@REPORTBY varchar(150),
	@REPORTTO_HRID int,
	@REPORTTO varchar(150),
	@DESCRIPTION varchar(2000),
	@INCIDENTOCCUR int,
	@SITENUM varchar(20),
	@SITENAME varchar(30),
	@SITESTATE varchar(24),
	@SITEDIVISION varchar(24),
	@SITEBUSINESS varchar(24),
	@SPECAREA varchar(100),
	@ADDRESS1 varchar(100),
	@ADDRESS2 varchar(100),
	@SUBURB varchar(60),
	@STATE char(3),
	@POSTCODE char(4),
	@RESPMANAGER_POSID int,
	@RESPMANAGER_POSITION varchar(140),
	@SITEMANAGER_POSID int,
	@SITEMANAGER_POSITION varchar(140),
	@ACTIONTAKENBY_HRID int,
	@ACTIONTAKENBY varchar(100),
	@ACTIONTAKEN varchar(2000),
	@CONSEQUENCE char(10),
	@LIKELIHOOD char(10),
	@INITTREATMENT int,
	@TREATMENTPROVIDED varchar(2000),
	@PD_FIXEDPLANT int,
	@PD_BUILDING int,
	@PD_MOBILEPLANT int,
	@PD_PORTABLEEQUIP int,
	@ENVIRONMENTDETAILS char(10),
	@DATETIMEENTERED datetime,
	@SITEID int,
	@PREVMANAGER_POSID int,
	@ALARP int,
	@HAZARDCLASS char(10),
	@HAZARDCAT char(10),
	@INCTYPE_CONVERSATION int,
	@CONVERSATIONCLASS int,
	@CONVERSATIONWITH int,
	@CONVERSATIONREASON int,
	@CONVERSATIONREADYTOCLOSE int,
	@INCTYPE_REGULATORYINVOLVEMENT int,
	@AUTHORITYTYPE char(10),
	@AUTHORITYNAME varchar(100),
	@FULLNAMESOFREGULATOR varchar(200),
	@INVOLVEMENTTYPE char(10),
	@INVOLVEMENTCATEGORY char(10),
	@DATEREGULATORYINVOLVEMENTWASISSUED datetime,
	@REGULATORYINVOLVEMENTISSUEDTO_HRID int,
	@REGULATORYINVOLVEMENTISSUEDTO varchar(150),
	@DATEREGULATORYINVOLVEMENTWASRECEIVED datetime,
	@RISKOFPENALTY char(10),
	@POTENTIALFINECOST numeric(14,2),
	@ACTUALFINECOST numeric(14,2),
	@REGULATORYINVOLVEMENTALARP int,
	@Timestamp timestamp output
as
declare @ts timestamp
set @ts = @@DBTS + 1

Update	INC_INCIDENT
Set	USERINCNO = @USERINCNO,
	STATUS = @STATUS,
	DATEENTERED = @DATEENTERED,
	FORMHRID = @FORMHRID,
	FORMEMPNO = @FORMEMPNO,
	FORMFIRSTNAME = @FORMFIRSTNAME,
	FORMSURNAME = @FORMSURNAME,
	DATECLOSED = @DATECLOSED,
	INCTYPE_INJURY = @INCTYPE_INJURY,
	INCTYPE_NEARMISS = @INCTYPE_NEARMISS,
	INCTYPE_HAZARD = @INCTYPE_HAZARD,
	INCTYPE_ENVIMPACT = @INCTYPE_ENVIMPACT,
	INCTYPE_PROPDAMAGE = @INCTYPE_PROPDAMAGE,
	INCTYPE_MOTOR = @INCTYPE_MOTOR,
	CONFIDENTIAL = @CONFIDENTIAL,
	INCIDENTDATE = @INCIDENTDATE,
	INCIDENTTIME = @INCIDENTTIME,
	REPORTDATE = @REPORTDATE,
	REPORTTIME = @REPORTTIME,
	REPORTBY_HRID = @REPORTBY_HRID,
	REPORTBY = @REPORTBY,
	REPORTTO_HRID = @REPORTTO_HRID,
	REPORTTO = @REPORTTO,
	DESCRIPTION = @DESCRIPTION,
	INCIDENTOCCUR = @INCIDENTOCCUR,
	SITENUM = @SITENUM,
	SITENAME = @SITENAME,
	SITESTATE = @SITESTATE,
	SITEDIVISION = @SITEDIVISION,
	SITEBUSINESS = @SITEBUSINESS,
	SPECAREA = @SPECAREA,
	ADDRESS1 = @ADDRESS1,
	ADDRESS2 = @ADDRESS2,
	SUBURB = @SUBURB,
	STATE = @STATE,
	POSTCODE = @POSTCODE,
	RESPMANAGER_POSID = @RESPMANAGER_POSID,
	RESPMANAGER_POSITION = @RESPMANAGER_POSITION,
	SITEMANAGER_POSID = @SITEMANAGER_POSID,
	SITEMANAGER_POSITION = @SITEMANAGER_POSITION,
	ACTIONTAKENBY_HRID = @ACTIONTAKENBY_HRID,
	ACTIONTAKENBY = @ACTIONTAKENBY,
	ACTIONTAKEN = @ACTIONTAKEN,
	CONSEQUENCE = @CONSEQUENCE,
	LIKELIHOOD = @LIKELIHOOD,
	INITTREATMENT = @INITTREATMENT,
	TREATMENTPROVIDED = @TREATMENTPROVIDED,
	PD_FIXEDPLANT = @PD_FIXEDPLANT,
	PD_BUILDING = @PD_BUILDING,
	PD_MOBILEPLANT = @PD_MOBILEPLANT,
	PD_PORTABLEEQUIP = @PD_PORTABLEEQUIP,
	ENVIRONMENTDETAILS = @ENVIRONMENTDETAILS,
	DATETIMEENTERED = @DATETIMEENTERED,
	SITEID = @SITEID,
	PREVMANAGER_POSID = @PREVMANAGER_POSID,
	ALARP = @ALARP,
	HAZARDCLASS = @HAZARDCLASS,
	HAZARDCAT = @HAZARDCAT,
	INCTYPE_CONVERSATION = @INCTYPE_CONVERSATION,
	CONVERSATIONCLASS = @CONVERSATIONCLASS,
	CONVERSATIONWITH = @CONVERSATIONWITH,
	CONVERSATIONREASON = @CONVERSATIONREASON,
	CONVERSATIONREADYTOCLOSE = @CONVERSATIONREADYTOCLOSE,
	INCTYPE_REGULATORYINVOLVEMENT = @INCTYPE_REGULATORYINVOLVEMENT,
	AUTHORITYTYPE = @AUTHORITYTYPE,
	AUTHORITYNAME = @AUTHORITYNAME,
	FULLNAMESOFREGULATOR = @FULLNAMESOFREGULATOR,
	INVOLVEMENTTYPE = @INVOLVEMENTTYPE,
	INVOLVEMENTCATEGORY = @INVOLVEMENTCATEGORY,
	DATEREGULATORYINVOLVEMENTWASISSUED = @DATEREGULATORYINVOLVEMENTWASISSUED,
	REGULATORYINVOLVEMENTISSUEDTO_HRID = @REGULATORYINVOLVEMENTISSUEDTO_HRID,
	REGULATORYINVOLVEMENTISSUEDTO = @REGULATORYINVOLVEMENTISSUEDTO,
	DATEREGULATORYINVOLVEMENTWASRECEIVED = @DATEREGULATORYINVOLVEMENTWASRECEIVED,
	RISKOFPENALTY = @RISKOFPENALTY,
	POTENTIALFINECOST = @POTENTIALFINECOST,
	ACTUALFINECOST = @ACTUALFINECOST,
	REGULATORYINVOLVEMENTALARP = @REGULATORYINVOLVEMENTALARP
Where	INCID = @INCID
And	timestamp = @Timestamp

if @@ROWCOUNT=0
	RAISERROR('Another user has updated this Table (stored procedure: PIncIncident$INC_INCIDENTModify)',15,1)
Set @Timestamp = @ts


GO



/****** Object:  StoredProcedure [dbo].[PIncIncident$INC_INCIDENTDelete]    Script Date: 6/28/2017 12:45:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER Procedure [dbo].[PIncIncident$INC_INCIDENTDelete]
	@Timestamp varbinary(8)
as
Delete	from INC_INCIDENT
Where	timestamp = @Timestamp

if @@ROWCOUNT = 0
	RAISERROR('Another user has updated this table (stored procedure: PIncIncident$INC_INCIDENTDelete)',15,1)

GO


